import { Inter } from "next/font/google";
import "./globals.css";
import { CartContextProvider } from "@/context/CartContext";
import NavBar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Glass-O-Gram",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <CartContextProvider>
      <html lang="en">
        <body className={inter.className}>
          <NavBar />
          {children}
        </body>
      </html>
    </CartContextProvider>
  );
}
